@startuml

title Trenowanie modelu uczenia maszynowego\n

start

partition "Przygotowanie danych"{
    repeat
        :Wybór odpowiedniej etykiety gestu;
        :Przesunięcie układu współrzędnych;
        :Zapis danych do wektora;
        :Normalizacja wektora względem największej wartości;
        :Zapis danych do pliku CSV;
    repeat while (nowy gest?) is (tak)
    ->nie;
}

stop

@enduml