@startuml

skinparam defaultTextAlignment center

start

partition "Przygotowanie danych"{
:Algorytm przygotowujący \ndane do zapisu w pliku CSV.;
}

partition "Przygotowanie danych do trenowania"{
:Dane zostają odpwiednio \nrozdzielone i przygotowane do \ntrenowania.;
}

partition "Trenowanie modeli"{
:Trenowanie paru wybranych \nmodeli uczenia maszynowego.;
}


stop

@enduml